language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-umd' ]; then cd .. && eval "mv $currentfolder generator-umd" && cd generator-umd; fi

